name: Sandbox - Build and Deploy
'on':
  push:
    branches: master
jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and deploy artifact to sandbox
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
          run: mvn -B deploy -DmuleDeploy -s .maven/settings.xml
        env:
            NEXUS_USERNAME: '${{ secrets.NEXUS_USERNAME }}'
            NEXUS_PASSWORD: '${{ secrets.NEXUS_PASSWORD }}'
            PLATFORM_USERNAME: '${{ secrets.CONNECTED_APP_CLIENT_IDD }}'
            PLATFORM_PASSWORD: '${{ secrets.CONNECTED_APP_CLIENT_SECRET }}'
            BUS_GROUP_ID: '${{ secrets.GROUP_IDDD }}'
